### ISSUE TITLE
Notification sound goes of when nothing is new (2.9.6 update)

### ISSUE THREAD

**Issue by Gilligan8** [FMaz008/VineHelper#133]
After the 2.9.6 update, the notification sound is going off every few seconds (30'ish) but there is nothing new in my list (I have it set to only show Free and KW)

My Pavlov effect is in full swing. LOL

**Comment by FMaz008** [comment]
Do you have on screen notifications enabled ?

**Comment by 1920x1200** [comment]
https://github.com/FMaz008/VineHelper/issues/129

**Comment by FMaz008** [comment]
This is a different issue. Issue 129 is getting sound when an actual new item is received but filtered out.

My understanding is that you constantly get sound every 30 seconds even when no new item are received.

Correct?

**Comment by Gilligan8** [comment]
I do not have screen notifications on.

I'll time it and see if it's consistent or random but "about" 30 seconds.

**Comment by Gilligan8** [comment]
Definitely random... between 30 seconds and 2 mins typically.

I think it's like you said, every new item is causing a sound but the filter is not showing them.

Used to be only things that showed caused the sound.

**Comment by FMaz008** [comment]
I've found 2 ways this could occur:
1. If you have a list of hidden keywords and enable the option to apply that list to your notifications, then the items are hidden after being added (in practice you don't see it). This will trigger a sound for the hidden item.
2. If you have the filtering on, same deal, hidden items will still trigger sound.

I have coded fixes for both issues and should be releasing them soon.
Does any of those 2 scenarios seem to explain your issue ?

**Comment by Gilligan8** [comment]
No hidden keywords... I did have some before the update but the update wiped out all of my keywords.

I have filtering turned on to only show Zero ETV and KW's... I'm assuming you aren't talking about that though because then this would be happening to everyone wouldn't it?

**Comment by urbanmoon** [comment]
I've been having the same problem. I do have keywords on both devices this is doing it on. I did have on-screen notifications but had to turn them off due to a new problem with that.

**Comment by FMaz008** [comment]
Any errors from notifications.js in the developer's console ?

**Comment by urbanmoon** [comment]
Here is the only thing I was able to find (I don't have Brenda enabled). This is the same screen, one shot of the red X, the other what the X said. 

![Screenshot_20241002_172501](https://github.com/user-attachments/assets/91074b6c-df87-4c35-965d-c51cdc9d0791)
![Screenshot_20241002_172450](https://github.com/user-attachments/assets/72fbd5d7-bc2b-4c89-9232-f2238e3bd2ea)

**Comment by FMaz008** [comment]
Update your extension, that bug was fixed in version 2.9.8, see commit c52d9ec653c478e0a621eb924177afa083aded48

:)

**Comment by Gilligan8** [comment]
I've upgraded to 2.9.9 and the problem of notification sounds going off still exist.

Specifically the "Free ETV" sound (Upgrade sound) as I have a different sound for KW results.
