### ISSUE TITLE
[Bug]: Unexpectly opens random AI tab in different window

### ISSUE THREAD

**Issue by disconn3ct** [FMaz008/VineHelper#216]
### Bug Description

Notification monitor is opening random new AI tabs in unrelated windows

### Steps to Reproduce

1. Open monitor
2. Change windows and do other work
3. Unexpectedly a background tab will open in the new window leading to https://www.amazon.com/vine/vine-items?queue=encore&page=6#AR
4. 

### Expected Behavior

not that, never that

### Browser

Librewolf

### Version Number

138.0.3-1

**Comment by FMaz008** [comment]
So instead of the tab opening in the window with the notification monitor, it opens in the current window ?
I can see that being a problem... I'll look into it.

**Comment by FMaz008** [comment]
Fixed as of 3.4.3, but the code is ridiculously complex. I tested it good but we'll see...

**Comment by FMaz008** [comment]
Will close for housekeeping, but don't hesitate to re-open if it is still not working properly.

**Comment by disconn3ct** [comment]
Still happening in 3.4.4 :( Two tabs opened in my current window.

**Comment by FMaz008** [comment]
Is you current window have a monitor tab openned in it?

**Comment by FMaz008** [comment]
You might want to read the change log as for the why. (System -> Display changelog. Refresh a vine page to get the popup again), but I'm having a hard time reproducing this issue.

The code is supposed to trigger only if you are actively in the notification monitor, or if the notification monitor is in an off-focussed window.

You are in the second case, which then is supposed to get the window Id where a tabURL contains `#monitor` and open the new tab in that window.

Are you somehow having a tab in your active window with `#monitor` in the URL ?

**Comment by FMaz008** [comment]
The opt out option is not to use the Notification Monitor, which will turn off this behavior. As I said, the issue was that you have people doing the work and browsing, so contributing, for a large majority of people not browsing and just sitting in front of the monitor all day, reaping the rewards of those putting in the work.

If you are browsing (assuming in the same window than the notification monitor tab is in), the auto-load won't happen. It's really a measure intended to force "idlers" to contribute their fair share.

As for the ToS, it's definitely skirting the line, but every other extensions (not just UV) have been offering auto refresh for a long time now. VH was pretty much the last one not to offer it. Technically, such a crowd distributed system is gentler on Amazon's server than having thousand of people refreshing every 10 seconds. But yes depending on your interpretation, it could be seen as going against some of Amazon's ToS (but not Vine CoU).

I based my decision on other extensions having used aggressive auto-refreshers for over 2 years now without any reported problem.

It is possible LibreFox behaves differently from Chrome or Firefox. I'll have to install it and do some further testing as so far my testing for this issue has been in Firefox, which behave properly.

**Comment by disconn3ct** [comment]
It opened 139 background tabs (plus or minus a couple) overnight on my desktop.

Just under one hundred and fifty background tabs.

**Comment by FMaz008** [comment]
Are you saying it is not closing them?

**Comment by FMaz008** [comment]
I just installed librewolf and it's working as intended in my end (tabs are closing after being open). Can you describe me your setup in term of tabs and windows, so I can try to reproduce your exact situation ?
